### ISSUE TITLE
Wireframe and user test stories for epic2

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/learn.duke#157]
confirm if users need to be communicated about role mapping
	* handoff atom-named sketches of screens to WM
	* focus on meaningful feedback from users

**Comment by LASHirsh** [comment]
Still in progress, not ready for comment yet, but posting here so we can discuss/reference as needed.

https://preview.uxpin.com/97f1536f1e1180fb99f4e5e05651cf146eef0747

**Comment by swwalker** [comment]
Is this still an open item?
