### ISSUE TITLE
Review app design/styles for inspiration

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/learn.duke#158]

**Comment by profmikegreene** [comment]
I've been getting a lot of design inspiration from youtube and github recently. Some specific pages
https://www.youtube.com/my_videos?o=U
https://www.youtube.com/account_notifications
https://github.com/settings/notifications

Google Inbox
https://inbox.google.com/u/1/

**Comment by profmikegreene** [comment]
Slack's app is good, but their web interface is nice as well
https://dukeli.slack.com/admin/stats

**Comment by bap13** [comment]
@profmikegreene These samples are very clean and somewhat austere and programatic - they seem to show more UI element layouts (with cool logo samples). Are these examples of the FEEL you are looking for from the new Toolkits? 

I believe I (in partnership with Jen) need to send out a survey, or meet with smaller groups of people, to help identify the needed design styles that would express the personality of the product as a whole, while supporting the Duke brand and making the UI and UX feel connected.

If functional and clean is what is wanted, there is absolutely nothing wrong with that. My design style is clean and minimal. I need to be sure someone isn't expecting "sleek and sexy" and gets delivered "clean and minimal" and is disappointed.

**Comment by bap13** [comment]
I love the slack web interface! Pops of color from icons, friendly tone.

**Comment by profmikegreene** [comment]
I've been trying to think of sites with more interactivity than basic websites. Do you want more diverse design examples even if the way a user interacts with the site will be fundamentally different than with our site @bap13 ?

Also, you just taught me that you can "thumbs up" someone's comment. Thanks!

**Comment by bap13** [comment]
You are accurate for doing so, and these are helpful. @LASHirsh and I just spoke, and I will attend Monday afternoon's meeting to ask some specific questions of those in attendance to help guide the look and feel. I am guessing will take less than an hour.

I will need to talk to more people, including Matthew, but Monday will be a good start.

**Comment by bap13** [comment]
@profmikegreene I am working on a survey to send to the team to identify styles and design direction, so I will not be attending today's meeting after all. That will come in the next few days.

**Comment by profmikegreene** [comment]
I hate modal windows, just going to throw that out there.

**Comment by hrvalli** [comment]
Some gorgeous websites:
http://www.feedmusic.com/
http://projectsunday.net/
http://experience.mausoleodiaugusto.it/en/

**Comment by JustinJohnsen** [comment]
Here are some that appeal to me. I gravitate toward clean and minimal (and functional!!) often, too.

http://www.hemingwayapp.com

https://www.desmos.com/calculator

http://note.ly/

https://easypolls.net

https://codepen.io
Example user page:  https://codepen.io/oliviale/pen/ELPvLM

**Comment by JustinJohnsen** [comment]
This one I especially like, too.

http://www.wolframalpha.com

**Comment by profmikegreene** [comment]
I like some things about new gmail. This for ex https://twitter.com/dcseifert/status/991318142981898240?s=21
