### ISSUE TITLE
Add DWS users to Github

### ISSUE THREAD

**Issue by bap13** [DukeLearningInnovation/learn.duke#163]
Request Github id's for:
- Ryn Nasser
- Jen Hubbard= curiousmustard
- JIllian Warren

Post here then reassign to Michael to add.

**Comment by bap13** [comment]
@profmikegreene while i wait for other id's, can you go ahead and Jen Hubbard to this project: Curiousmustard

thanks!

**Comment by profmikegreene** [comment]
All three should have email invites waiting for them @bap13
