### ISSUE TITLE
Who and what attributes can we search on in LDAP?

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/learn.duke#179]
Based on our wireframes, we want individual search of these attributes
* name
* email

and bulk search of these attributes
* DUID
* netid
* email
* onelink id

**Comment by outten45** [comment]
I talked with Curt last week. We can query about duid, email and name for sure. I forgot to ask about netid, but that should be possible. He wasn't sure about the onelink id (or if it would make sense to query on that one anyway).
