### ISSUE TITLE
review of tsugi for inclusion in the project.

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/learn.duke#181]

**Comment by profmikegreene** [comment]
learn.duke supporting LTI apps is really what we want to accomplish. tsugi is just one way to accomplish it. In LTI-land, learn.duke needs to play the role of LTI consumer. One use case in particular to think about is a faculty who wants to use several tools like Voicethread and PlayPosit but not Sakai. 

Right now there is no provisioning of those tools without using Sakai and edtech tools come with LTI provisioning baked in which makes it the path of least resistance for our team, but perhaps not for this project/this team. I look forward to discussing it with you both more!

**Comment by outten45** [comment]
Capturing some brief notes from this morning, Liz, Noah and myself talked about LTI and tsugi. In general, LTI seems doable (maybe from within Toolkits). We didn't get very deep into it, but we did get far enough to have some questions about the workflow and how the ability to add tools would work (is it at the course or institution level). 
Given there are some unknowns, it would probably be better to work through this after the initial MVP.
