### ISSUE TITLE
Provide names of at least 8 real courses

### ISSUE THREAD

**Issue by bap13** [DukeLearningInnovation/learn.duke#186]
Realized we needed REAL names of courses to see how they worked on the card designs. @profmikegreene  can you provide us the names of at least 8 classes so we can see how cards work with real course names of different character lengths? Feel free to reassign someone else to provide. 

Could we have the names by mid-week?
thanks!

**Comment by bap13** [comment]
@swwalker I do not know how to associate this issue with sprint #4.

**Comment by ewendland23** [comment]
Here are the longest titles from real course examples in Toolkits now.  The first bit is the title and the second part is the 'tuple' we use to uniquely identify the course:

- "ENGLISH 181BS-01: Arts In N Y: Thematic Approach, Summer1 2012", ENGLISH:181BS:01:1181:1405
- "THEATRST 100S-01: Communicat, Improv, & Business, Summer2 2012", THEATRST:100S:01:1408:1410
- "ACCOUNTG 245F-00A: Intro To Financial Accounting, Summer2 2012", ACCOUNTG:245F:00A:1656:1410
- "HISTORY 390S-1-01: Digital Hist& Humanities (Top), Spring 2017", HISTORY:390S-1:01:4880:1590
- "ARTS&SCI 101D-01D: Intro To Quant/Qual Reasoning, Summer2 2017", ARTS&SCI:101D:01D:1397:1610
- "HISTORY 790S-10-01: Rdngs Empr/Colonial Encounters, Spring 2018", HISTORY:790S-10:01:3994:1630
- "HISTORY 790S-10-01: Rdngs Empr/Colonial Encounters, Spring 2014", HISTORY:790S-10:01:3254:1470
- "DECISION 202F-00A: Quantitative Business Analysis, Summer2 2012", DECISION:202F:00A:1654:1410
- "HISTORY 790S-10-01: Rdngs Empr/Colonial Encounters, Spring 2013", HISTORY:790S-10:01:3572:1430
- "HLTHMGMT 541CI-301: Clinical Imformatics Practicum, Spring 2013", HLTHMGMT:541CI:301:7964:1430
- "HLTHMGMT 540CI-401: Secondary Use Of Hlthcare Data, Summer1 2013", HLTHMGMT:540CI:401:2102:1445
- "PHYSICS 131S-1-01M: Intro Seminar On Big Questions, Summer2 2014", PHYSICS:131S-1:01M:1697:1490
- "PHYSICS 131S-1-01M: Intro Seminar On Big Questions, Summer2 2017", PHYSICS:131S-1:01M:1013:1610
- "ENGLISH 290S-2-01: Sp Top 18 Th & 19 Th Century Lit, Spring 2018", ENGLISH:290S-2:01:3838:1630
- "HLTHMGMT 317CI-401: Secondary Use Of Hlthcare Data, Summer1 2012", HLTHMGMT:317CI:401:1588:1405
- "ENVIRON 357L-001 - SATELLITE REMOTE SENSING_JenniferSwenson_fall_2010", ENVIRON:357L:001:5564:1340
- "ENVIRON 357L-01L - SATELLITE REMOTE SENSING JenniferSwenson_fall_2010", ENVIRON:357L:01L:5565:1340

**Comment by bap13** [comment]
Thank you @ewendland23, this is extremely helpful... and enlightening.
