### ISSUE TITLE
Course Title formatting

### ISSUE THREAD

**Issue by bap13** [DukeLearningInnovation/learn.duke#187]
We need confirmation from Learning Innovation of how the course titles in issue #186 can be broken apart and formatted. 

Can you confirm that we can pull out and reorder (and potentially add different styling to) the various color-coded areas on the course titles. It is also suggested to filter the order of cards by "Title" and "Course Number". So that may affect styling decisions.

@profmikegreene 

![card_class-name_mapping](https://user-images.githubusercontent.com/38254766/41421907-cdf3bc12-6fc5-11e8-86d5-23cd4ca634ad.png)

**Comment by profmikegreene** [comment]
In terms of display, we can do whatever the users desire. The display shows semester elsewhere, so removing it from the course card makes sense. If users ask for it back during testing, we can adjust.

Several users in our testing this week have stated the ENVIRON 375L 001 is what they are looking for and want to be prioritized in the display, not 'Satellite remove sensing'. I'd like to see mockups of those two switched in the card header.

In Sakai we use periods as the separators, but I approve the use of spaces here. Is anyone familiar with how Dukehub displays course titles to users?

**Comment by bap13** [comment]
This was decided on and ok to implement. Closing issue.
