### ISSUE TITLE
Demo look and feel to stakeholders

### ISSUE THREAD

**Issue by bap13** [DukeLearningInnovation/learn.duke#191]
Get feedback and/or approval on design direction for app from stakeholders. Working on setting up a meeting this sprint.

**Comment by swwalker** [comment]
@bap13 - can you comment on this issue the results of the feedback session held earlier in the week and close this item?  Thanks.

**Comment by bap13** [comment]
@curiousmustard and I met with stakeholders to presetn take-aways form interanl design survey and demo style options. The following design direction was chosen: https://projects.invisionapp.com/boards/GP3NU02SZAY/

We will move forward using this for all newly designed pages. Closing issue.
