### ISSUE TITLE
Is button disabled after user adds app (except custom links) to a kit?

### ISSUE THREAD

**Issue by curiousmustard** [DukeLearningInnovation/learn.duke#210]
Is the "App Added to kit" button on an app card in a disabled state? Or clickable, if so, what does it do? I'm trying to figure out if I need 2 disabled states for this button.

**Comment by LASHirsh** [comment]
Yes, in this first version, the button is disabled. (In the future, we'd like for people to be able to provision more than one instance of the app for a course as appropriate/needed). Thanks for checking!
