### ISSUE TITLE
[COURSE SETUP] As a faculty member, I want to set up the group membership and provision apps for a particular course.

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/learn.duke#34]

**Comment by JustinJohnsen** [comment]
Are faculty always/often responsible for managing membership in the learning community (course)? Would others need to have this authority? How do we manage the powers associated with roles?

**Comment by JustinJohnsen** [comment]
![img_180103111137750](https://user-images.githubusercontent.com/13791075/34528590-594761ca-f077-11e7-9186-3714005e91b5.jpg)

**Comment by profmikegreene** [comment]
@JustinJohnsen you're right on the roles. We haven't discussed official role names yet, but it will be more robust than only instructor of record gets admin access. Current toolkits roles below.


Toolkits Role | Sakai Course Site Equivalent
--- | ---
Instructor | Instructor
Manager | Instructor
TA | Teaching Assistant
Developer | Course Builder
Mentor | Teaching Assistant
Student | Student
Auditor | Student
Visitor | Visitor

Toolkits Role | Sakai Project Site Equivalent
---|---
Admin | maintain
Contributor | access
Visitor | Visitor


Toolkits Role | WordPress Equivalent
--- | ---
Instructor | Administrator
Manager | Administrator
TA | Administrator
Admin | Administrator
Developer | Editor
Mentor | Editor
Contributor | Editor
Student | Author
Visitor/Auditor | Subscriber
