### ISSUE TITLE
As a faculty member, I want to browse for apps in the "App store" because I am interested in seeing what is available and would work well with my course.

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/learn.duke#38]

**Comment by JustinJohnsen** [comment]
Agree. I think a 'copy course tool set' option may be nice to offer, but not MVP1.

**Comment by profmikegreene** [comment]
@JustinJohnsen you should write that up as a separate user story sounds like a cool feature!

**Comment by profmikegreene** [comment]
Refer to #48 for app store browsing
