### ISSUE TITLE
SISS groups are auto-created, faculty don't have to create the group in learn.duke or group-manager

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/learn.duke#63]
This is a technical assumption, can @ewendland23 confirm or do we need to ping IDM or SISS team?

**Comment by ewendland23** [comment]
All course rosters are set up in Grouper automatically.  There is a group for the instructors and the students.  Fascinating fact- Cross-listed courses have groups for every course listed with all members of the course in each listing.
